package com.backend.dto.ai;

public enum AssistantIntent {
    NORMAL_CHAT,
    RECOMMEND_BY_BUDGET,
    RECOMMEND_BY_PURPOSE,
    RECOMMEND_BY_BRAND,
    EXPLAIN_COMPONENT,
    COMPARE_COMPONENTS,
    CHECK_COMPATIBILITY,
    RECOMMEND_CHEAPER_ALTERNATIVE,
    RECOMMEND_BETTER_UPGRADE
}